services:
  - type: web
    name: secret-santa
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: SANTA_ADMIN_NAME
        value: admin
      - key: DATABASE_URL
        fromDatabase:
          name: secret-santa-db
          property: connectionString

databases:
  - name: secret-santa-db
    plan: free

